sudo: required

language: java
jdk:
  - openjdk8

before_script:
  - wget https://services.gradle.org/distributions/gradle-6.0-bin.zip
  - unzip gradle-6.0-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.0
  - export PATH=$GRADLE_HOME/bin:$PATH

addons:
  sonarcloud:
    organization: "awt-04"
    token:
      secure: $SONAR_TOKEN

script:
  - gradle test
  - sonar-scanner
  - gradle check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
